### ISSUE TITLE
 Container command not found or does not exist

### ISSUE THREAD

**Issue by hopewise** [shincoder/homestead-docker#12]
I could not start the container, I got this error:

```
$ docker-compose up -d
Removing lumen
Recreating 5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_5136e763cf0f_homesteaddocker_lumen_1
[31mERROR[0m: Container command not found or does not exist.
```

Any hint?

**Comment by jaouadk** [comment]
Did u modify the contents of Dockerfile/docker-compose.yml?

**Comment by hopewise** [comment]
Yes, I am on windows 10, my app will be on `C:\Users\Samir\PhpstormProjects\my-project-apis`

```
lumen:
    image: shincoder/homestead
    restart: always
    ports:
        - "8080:80" # web
        - "2280:22" # ssh
        - "35729:35729" # live reload
        - "9876:9876" # karma server
    volumes:
        - ~/.composer:/home/homestead/.composer # composer caching
        - ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
        - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
        - C:\Users\Samir\PhpstormProjects\my-project-apis:/apps # all apps
        - ~/apps/volumes/nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
        - ~/apps/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
    external_links:
        - postgis:postgis
```
