### ISSUE TITLE
can you give me some example?

### ISSUE THREAD

**Issue by zhanghuid** [shincoder/homestead-docker#32]
i am work in window operate system.

how can i use navicat to connect the mysql?

thank you for your help.

**Comment by jaouadk** [comment]
expose port 3306 to your system, then you'll be able to connect to mysql.

Edit your docker-compos.yml, then use 127.0.0.1 as the IP address, if it doesn't work, use docker's own IP.

```
mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
        - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - ~/volumes/mysql:/var/lib/mysql
```

Here is a fork that can help you setup also your folder mappings:

https://github.com/lfserrra/homestead-docker/commit/e2f1b85d2c35a8406026d1620c8176f345fcdb81
